# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/bytedance/cocoapods_sdk_source_repo.git'
source 'https://github.com/volcengine/volcengine-specs.git'

target 'YYTFramework' do

pod 'Firebase/AdMob'
pod 'BaiduMobAdSDK'
pod 'GDTMobSDK'
pod 'Ads-CN'

end

