# Uncomment this line to define a global platform for your project
platform :ios, '12.0'
# Uncomment this line if you're using Swift
# use_frameworks!
use_modular_headers!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/bytedance/cocoapods_sdk_source_repo.git'
source 'https://github.com/volcengine/volcengine-specs.git'

target 'YYTFramework' do

pod 'Firebase/Analytics'
pod 'Google-Mobile-Ads-SDK'
pod 'BaiduMobAdSDK', '4.83'
pod 'GDTMobSDK'
pod 'Ads-CN'
pod 'LookinServer', :configurations => ['Debug']
pod 'Masonry'

end

