# Uncomment this line to define a global platform for your project
platform :ios, '12.0'
# Uncomment this line if you're using Swift
# use_frameworks!
use_modular_headers!
if ENV['LINT'] != '1'
  plugin 'cocoapods-byte-csjm'
  use_gm_adapter_update! # 如果插件提供了 DSL 方法，也一并禁用
end


source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/bytedance/cocoapods_sdk_source_repo.git'
#source 'https://github.com/volcengine/volcengine-specs.git'

target 'YYTFramework' do
  
#gm_release_target!

# 请在测试环境中使用，切勿将测试工具带到生产环境
#pod 'BUAdTestMeasurement-beta', '6.7.0.3', :configuration => 'Debug'

pod 'Ads-Fusion-CN-Beta', '6.0.0.5', :subspecs => ['CSJMediation']
# 引入使用到的ADN SDK，开发者请按需引入
pod 'GDTMobSDK', '4.14.63'
pod 'BaiduMobAdSDK', '5.34'
pod 'Google-Mobile-Ads-SDK', '10.0.0'

#pod 'Ads-CN-Beta', '6.7.0.3', :subspecs => ['CSJMediation']
## 引入使用到的ADN SDK，开发者请按需引入
#pod 'GDTMobSDK', '4.15.10'
#pod 'BaiduMobAdSDK', '5.370'
#pod 'Google-Mobile-Ads-SDK', '10.0.0'

#pod 'Firebase/Analytics'
pod 'Masonry'

# 仅在 Debug 配置中使用的 Pods
pod 'LookinServer', :configurations => ['Debug']
#pod 'BUAdTestMeasurement', :configurations => ['Debug']

end

